project:
  type: book

book:
  sidebar:
    logo: assets/favicon-red.svg
  favicon: assets/favicon-red.svg
  
  title: "Kapibara-Project"
  chapters:
    - part: "Moduły:"
    - part: "­ "
    - index.md
    - docs/features.md
    - text: "---"
    - summary.qmd
    - text: "---"
    - docs/authors.md

format:
  html:
    toc-title: "Rozdziały w tym module:"
    smooth-scroll: true
    theme:
      light: flatly
      dark: darkly