project:
  type: book

book:
  title: "Kapibara"
  author: 
  - "Mateusz Michalik"
  - "Jakub Liczbiński"
  - "Dariusz Karpiński"
  - "Piotr Jankowski"
  date: "27.12.2023"
  chapters:
    - index.md
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc-title: "Rozdziały w tym module:"
    smooth-scroll: true
    theme:
      light: flatly
      dark: darkly